sonar.organization=unq-desapp
sonar.projectKey=diazme1_desapp-2s-grupo-i
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.spec.ts
sonar.exclusions=dist/**,coverage/**,node_modules/**
sonar.coverage.exclusions=src/main.ts
sonar.javascript.lcov.reportPaths=coverage/unit/lcov.info,coverage/integration/lcov.info
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
